export const ICON_TO_EMOJI = {
    'clear-day': '☀️',
    'clear-night': '🌕',
    'cloudy':  '☁️',
    'fog': '🌫️',
    'hail': '🌨',
    'partly-cloudy-day': '🌥',
    'partly-cloudy-night': '☁️',
    'rain-snow-showers-day': '🌧️',
    'rain-snow-showers-night': '🌧️',
    'rain-snow': '🌧️',
    'rain': '🌧️',
    'showers-day': '🌧️',
    'showers-night': '🌧️',
    'sleet': '❄️',
    'snow-showers-day': '❄️',
    'snow-showers-night': '❄️',
    'snow': '❄️',
    'thunder-rain': '⛈️',
    'thunder-showers-day': '⛈️',
    'thunder-showers-night': '⛈️',
    'thunder': '⛈️',
    'wind': '💨'
}